apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: gitops-repo
    namespace: flux-system
  path: ./Sample3/clusters/cluster-1/infra/
  prune: true
  wait: true
  timeout: 10m
