apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
spec:
  type: LoadBalancer
  externalIPs:
    - "13.95.8.148"
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx