apiVersion: batch/v1
kind: CronJob
metadata:
  name: start
  namespace: jobs
spec:
  schedule: "* * * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sa-job-runner
          containers:
          - name: hello
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - kubectl patch kustomizations.kustomize.toolkit.fluxcd.io gitops-layer-windowed -n gitops --patch '{"spec":{"suspend":false}}' --type merge;
          restartPolicy: Never