apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-config

spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-config
  template:
    metadata:
      labels:
        app: hello-config
    spec:
        containers:
          - name: hello-config-container
            image: docker.io/tamararahimi/hello-config:latest
            imagePullPolicy: Always
            ports:
              - containerPort: 4001
            env:
            - name: LIVE_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: live-configuration
                  key: hello.name
            - name: MW_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: mw-configuration
                  key: mw.name
                  optional: true