apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-generator
  labels:
    app: poc-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-generator
  template:
    metadata:
      labels:
        app: poc-generator
    spec:
      containers:
      - name: poc-generator-live-dummy
        image: bitnami/kubectl:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /app/configuration
          name: config
      volumes:
      - name: config
        configMap:
          name: poc-generator-configuration-live
          items:
          - key: "appconfig.yaml"
            path: appconfig.yaml